-- Create table for Semester Exams
create table public.exam_units (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    subject text not null,
    unit_number int not null,
    status text check (status in ('Not Started', 'In Progress', 'Completed')) default 'Not Started',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, subject, unit_number) -- Ensure unique unit per user
);

alter table public.exam_units enable row level security;

create policy "Users can view their own exam units" on public.exam_units
  for select using (auth.uid() = user_id);

create policy "Users can insert their own exam units" on public.exam_units
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own exam units" on public.exam_units
  for update using (auth.uid() = user_id);
